version: '2'
services:
  web:
    restart: always
    build: .
    image: ctb_model
    container_name: ctb_model
    environment:
      DB: db
    depends_on:
      - db
  db:
    image: neo4j:3.0.4
    container_name: ctb_model_neo
    environment:
      NEO4J_AUTH: none
    ports:
      - "7687:7687"
      - "7474:7474"
