version: '2'
services:
  tb2neo:
    build: .
    image: tb2neo 
    container_name: tb2neo 
    environment:
      DB: db
    depends_on:
      - db
  db:
    restart: always
    image: neo4j:3.2.1
    container_name: chado-neodb
    environment:
      NEO4J_AUTH: none
    volumes:
      - $HOME/neo4j/data:/data
    ports:
      - "7687:7687"
      - "7474:7474"
