version: '2'
services:
  goget:
    restart: always
    build: .
    image: goget
    container_name: goget
    environment:
      DB: db
    depends_on:
      - db
  db:
    image: neo4j:3.0.4
    container_name: neo
    environment:
      NEO4J_AUTH: none
    ports:
      - "7687:7687"
      - "7474:7474"